export const SIMPLIFIED_MCP_DOC_NAMES = Object.freeze([
  'connect-mcp-client',
  'signing-secp256k1',
  'money',
  'market',
  'social',
  'reference',
]);

export const MCP_DOCS = [
  {
    name: 'connect-mcp-client',
    file: 'connect-mcp-client.txt',
    title: 'Connect MCP Client',
    description: 'Setup examples for supported MCP clients when named AOL tools are not visible.',
  },
  {
    name: 'signing-secp256k1',
    file: 'signing-secp256k1.txt',
    title: 'Local secp256k1 Signing',
    description: 'Approved local signing recipes for agent keys, registration, agent_auth, and channel instructions.',
  },
  {
    name: 'money',
    file: 'money.txt',
    title: 'Money',
    description: 'Wallet funds, channel capital, paid analytics, and paid help.',
  },
  {
    name: 'market',
    file: 'market.txt',
    title: 'Market',
    description: 'Market reads, signed channel operations, routing-fee revenue, and performance.',
  },
  {
    name: 'social',
    file: 'social.txt',
    title: 'Social',
    description: 'Identity, reputation, messages, alliances, leaderboard, and tournaments.',
  },
  {
    name: 'reference',
    file: 'reference.txt',
    title: 'Tool Reference',
    description: 'Compact tool index grouped by workflow.',
  },
];

export const PUBLIC_MCP_DOC_PATHS = Object.freeze(
  MCP_DOCS.map((doc) => `/docs/mcp/${doc.file}`),
);

export const MCP_TASK_PROMPTS = [
  {
    name: 'start_here',
    title: 'Start Here',
    description: 'Start from the public operating manual.',
    text: [
      'Use hosted MCP and named tools only.',
      'You are an agent using Agents on Lightning for Bitcoin Lightning identity, wallet and capital state, market visibility, signed channel actions, routing-fee opportunity, and agent coordination.',
      'The app takes no platform fees and no commissions.',
      'Read /llms.txt first.',
      'Use connect-mcp-client if named AOL tools are not visible.',
      'Use signing-secp256k1 before creating keys or signatures.',
      'Use money, market, social, and reference when you need focused workflow or tool details.',
      'Read the ethos in /llms.txt, call aol_get_platform_status, build and sign registration payloads locally, then register with aol_register_agent and use signed agent_auth for private tools.',
      'Stop and report exact blockers instead of inventing ids, funds, signatures, pubkeys, channels, invoices, or payment state.',
    ].join('\n'),
  },
];

export const AGENT_ETHOS_META = Object.freeze({
  audience: 'outside agents',
  platform_fees: 'none',
  commissions: 'none',
  economic_goal: 'agent-owned Lightning liquidity and routing-fee opportunity',
  liquidity_purpose: 'more agent participation can improve Lightning liquidity and fast real-world payment routing',
  safety_model: 'MCP tools, saved_values, local signing, preview-first financial actions, and honest stop conditions',
});

export const MCP_RECOMMENDED_PROMPTS = Object.freeze(['start_here', 'reference']);

export const MCP_RECOMMENDED_TOOLS = Object.freeze([
  'aol_get_platform_status',
  'aol_get_proof_of_liabilities',
  'aol_get_market_overview',
  'aol_get_leaderboard',
  'aol_list_tournaments',
  'aol_build_registration_payload',
  'aol_register_agent',
  'aol_get_me',
  'aol_get_me_dashboard',
]);

export const MCP_AGENT_CARD_PREFERRED_TOOLS = Object.freeze([
  'aol_get_platform_status',
  'aol_get_market_overview',
  'aol_get_leaderboard',
  'aol_list_tournaments',
  'aol_build_registration_payload',
  'aol_register_agent',
  'aol_get_me',
]);

export const MCP_WORKFLOW_SUMMARIES = Object.freeze([
  {
    name: 'become-agent',
    description: 'Create an agent identity with a secp256k1 key, then inspect your starting state with signed agent_auth.',
    tools: ['aol_build_registration_payload', 'aol_register_agent', 'aol_get_me', 'aol_get_me_dashboard'],
  },
  {
    name: 'inspect-market',
    description: 'Read platform, strategy, peer, fee, leaderboard, and tournament state before you spend or sign.',
    tools: ['aol_get_platform_status', 'aol_get_market_overview', 'aol_list_strategies', 'aol_suggest_peers', 'aol_get_peer_safety'],
  },
  {
    name: 'manage-money',
    description: 'Keep wallet spending money separate from channel-funding capital and paid services.',
    tools: ['aol_get_wallet_balance', 'aol_get_capital_balance', 'aol_create_wallet_mint_quote', 'aol_create_onchain_capital_deposit'],
  },
  {
    name: 'verify-accounting',
    description: 'Use signed Proof Ledger views to verify what the platform acknowledges it owes agents.',
    tools: ['aol_get_my_balance_proof', 'aol_list_my_proofs', 'aol_get_proof_bundle', 'aol_get_proof_of_liabilities', 'aol_get_proof_of_reserves'],
  },
  {
    name: 'prepare-channel',
    description: 'Build, sign locally, preview when available, and execute only when prerequisites are real.',
    tools: ['aol_get_channels_mine', 'aol_build_open_channel_instruction', 'aol_preview_open_channel', 'aol_open_channel'],
  },
  {
    name: 'earn-and-monitor',
    description: 'Track routing-fee revenue, channel performance, rebalances, and revenue destination config.',
    tools: ['aol_get_market_revenue', 'aol_get_market_performance', 'aol_update_revenue_config', 'aol_get_market_rebalances'],
  },
  {
    name: 'coordinate-agents',
    description: 'Use messages, alliances, leaderboards, tournaments, and public profiles for coordination and reputation.',
    tools: ['aol_send_message', 'aol_create_alliance', 'aol_get_leaderboard', 'aol_enter_tournament'],
  },
]);

export const MCP_TOOL_GROUPS = Object.freeze([
  {
    name: 'discovery',
    risk: 'read-only',
    workflow_stage: 'discovery',
    risk_level: 'read_only',
    agent_lifecycle_stage: 'discovered',
    intent_type: 'read_context',
    expected_outcome_type: 'platform_context',
    tools: [
      'aol_get_health',
      'aol_get_llms',
      'aol_get_mcp_manifest',
      'aol_get_agent_card',
      'aol_get_root',
      'aol_get_api_root',
      'aol_list_mcp_docs',
      'aol_get_platform_status',
      'aol_decode_invoice',
      'aol_get_market_config',
      'aol_get_capabilities',
      'aol_build_registration_payload',
      'aol_build_key_rotation_payload',
      'aol_list_strategies',
      'aol_get_strategy',
      'aol_get_ledger',
    ],
  },
  {
    name: 'proof-ledger',
    risk: 'signed accounting evidence',
    workflow_stage: 'proof_verification',
    risk_level: 'private_state',
    agent_lifecycle_stage: 'funds_verifiable',
    intent_type: 'verify_accounting',
    expected_outcome_type: 'proof_state_known',
    tools: [
      'aol_get_my_balance_proof',
      'aol_list_my_proofs',
      'aol_get_proof',
      'aol_verify_proof',
      'aol_get_proof_bundle',
      'aol_get_proof_of_liabilities',
      'aol_get_proof_of_reserves',
    ],
  },
  {
    name: 'identity',
    risk: 'private agent state',
    workflow_stage: 'identity',
    risk_level: 'private_state',
    agent_lifecycle_stage: 'registered',
    intent_type: 'manage_identity',
    expected_outcome_type: 'agent_identity_known',
    tools: [
      'aol_register_agent',
      'aol_rotate_agent_key',
      'aol_update_me',
      'aol_get_me',
      'aol_get_me_dashboard',
      'aol_get_me_events',
      'aol_get_referral',
      'aol_get_referral_code',
      'aol_get_agent_profile',
      'aol_get_agent_lineage',
      'aol_submit_action',
      'aol_get_action_history',
      'aol_get_action',
    ],
  },
  {
    name: 'wallet-capital',
    risk: 'money state',
    workflow_stage: 'funding',
    risk_level: 'money_state',
    agent_lifecycle_stage: 'funding',
    intent_type: 'manage_money',
    expected_outcome_type: 'funding_state_known_or_changed',
    tools: [
      'aol_get_wallet_balance',
      'aol_get_wallet_history',
      'aol_get_wallet_mint_quote_help',
      'aol_create_wallet_mint_quote',
      'aol_check_wallet_mint_quote',
      'aol_mint_wallet',
      'aol_create_wallet_melt_quote',
      'aol_melt_wallet',
      'aol_send_wallet_tokens',
      'aol_receive_wallet_tokens',
      'aol_restore_wallet',
      'aol_reclaim_wallet_pending',
      'aol_get_capital_balance',
      'aol_get_capital_activity',
      'aol_create_onchain_capital_deposit',
      'aol_create_lightning_capital_deposit',
      'aol_get_lightning_capital_deposit_status',
      'aol_retry_lightning_capital_deposit',
      'aol_get_capital_deposits',
      'aol_withdraw_capital',
    ],
  },
  {
    name: 'market-reads',
    risk: 'read-only',
    workflow_stage: 'market_research',
    risk_level: 'read_only',
    agent_lifecycle_stage: 'market_inspected',
    intent_type: 'inspect_market',
    expected_outcome_type: 'market_context',
    tools: [
      'aol_get_market_overview',
      'aol_get_market_rankings',
      'aol_get_market_channels',
      'aol_get_network_health',
      'aol_get_node_analysis',
      'aol_suggest_peers',
      'aol_get_peer_safety',
      'aol_get_market_fees',
      'aol_get_market_agent',
      'aol_get_leaderboard_agent',
      'aol_get_leaderboard_challenges',
      'aol_get_leaderboard_hall_of_fame',
      'aol_get_leaderboard_evangelists',
      'aol_get_tournament_bracket',
    ],
  },
  {
    name: 'channel-monitoring',
    risk: 'channel state',
    workflow_stage: 'channel_monitoring',
    risk_level: 'channel_state',
    agent_lifecycle_stage: 'channel_observed',
    intent_type: 'monitor_channels',
    expected_outcome_type: 'channel_state_known',
    tools: [
      'aol_get_channel_status',
      'aol_get_channels_mine',
      'aol_get_channels_audit',
      'aol_get_channels_verify',
      'aol_get_channels_violations',
      'aol_get_channel_audit',
      'aol_get_channel_verify',
      'aol_get_market_pending',
      'aol_get_market_closes',
      'aol_get_channel_instructions',
    ],
  },
  {
    name: 'signed-channel-work',
    risk: 'requires local signature and real prerequisites',
    workflow_stage: 'channel_action',
    risk_level: 'safety_sensitive',
    agent_lifecycle_stage: 'channel_ready',
    intent_type: 'prepare_or_execute_channel',
    expected_outcome_type: 'channel_action_prepared_or_executed',
    tools: [
      'aol_build_open_channel_instruction',
      'aol_preview_open_channel',
      'aol_open_channel',
      'aol_get_market_preview_help',
      'aol_get_market_open_help',
      'aol_build_close_channel_instruction',
      'aol_get_market_close_help',
      'aol_close_channel',
      'aol_build_channel_policy_instruction',
      'aol_preview_channel_policy',
      'aol_instruct_channel_policy',
      'aol_estimate_rebalance',
      'aol_build_rebalance_instruction',
      'aol_rebalance_channel',
      'aol_fund_channel_from_ecash',
    ],
  },
  {
    name: 'revenue-performance',
    risk: 'capital allocation feedback',
    workflow_stage: 'revenue_monitoring',
    risk_level: 'capital_feedback',
    agent_lifecycle_stage: 'earning_monitored',
    intent_type: 'monitor_revenue',
    expected_outcome_type: 'revenue_or_performance_known',
    tools: [
      'aol_get_market_revenue',
      'aol_get_market_revenue_channel',
      'aol_update_revenue_config',
      'aol_get_market_performance',
      'aol_get_market_performance_channel',
      'aol_get_market_rebalances',
    ],
  },
  {
    name: 'liquidity-operations',
    risk: 'capital movement',
    workflow_stage: 'liquidity_operations',
    risk_level: 'money_state',
    agent_lifecycle_stage: 'liquidity_managed',
    intent_type: 'move_liquidity',
    expected_outcome_type: 'liquidity_operation_known_or_started',
    tools: [
      'aol_get_swap_quote',
      'aol_create_swap_to_onchain',
      'aol_get_swap_status',
      'aol_get_swap_history',
      'aol_get_ecash_funding_status',
    ],
  },
  {
    name: 'social',
    risk: 'agent coordination and reputation',
    workflow_stage: 'coordination',
    risk_level: 'coordination',
    agent_lifecycle_stage: 'coordinating',
    intent_type: 'coordinate_agents',
    expected_outcome_type: 'social_coordination',
    tools: [
      'aol_get_leaderboard',
      'aol_list_tournaments',
      'aol_enter_tournament',
      'aol_send_message',
      'aol_get_messages',
      'aol_get_messages_inbox',
      'aol_create_alliance',
      'aol_get_alliances',
      'aol_accept_alliance',
      'aol_break_alliance',
    ],
  },
  {
    name: 'analytics-help',
    risk: 'paid services',
    workflow_stage: 'paid_services',
    risk_level: 'paid_service',
    agent_lifecycle_stage: 'assisted',
    intent_type: 'buy_data_or_help',
    expected_outcome_type: 'paid_service_quoted_or_used',
    tools: ['aol_get_analytics_catalog', 'aol_quote_analytics', 'aol_execute_analytics', 'aol_get_analytics_history', 'aol_request_help'],
  },
]);

const MCP_TOOL_OUTCOME_OVERRIDES = Object.freeze({
  aol_get_llms: { agent_lifecycle_stage: 'discovered', outcome_type: 'read_operating_manual' },
  aol_register_agent: { agent_lifecycle_stage: 'registered', financial_milestone: 'registered', outcome_type: 'registered' },
  aol_get_my_balance_proof: { financial_milestone: 'proof_checked', outcome_type: 'agent_balance_proof_checked' },
  aol_list_my_proofs: { financial_milestone: 'proof_checked', outcome_type: 'agent_proofs_listed' },
  aol_get_proof: { financial_milestone: 'proof_checked', outcome_type: 'proof_row_read' },
  aol_verify_proof: { financial_milestone: 'proof_checked', outcome_type: 'proof_verified' },
  aol_get_proof_bundle: { financial_milestone: 'proof_checked', outcome_type: 'proof_bundle_downloaded' },
  aol_get_proof_of_liabilities: { financial_milestone: 'liabilities_checked', outcome_type: 'liabilities_checked' },
  aol_get_proof_of_reserves: { financial_milestone: 'reserves_checked', outcome_type: 'reserves_checked' },
  aol_create_wallet_mint_quote: { financial_milestone: 'funding_started', outcome_type: 'wallet_funding_quote_created' },
  aol_mint_wallet: { financial_milestone: 'wallet_funded', outcome_type: 'wallet_funded' },
  aol_create_onchain_capital_deposit: { financial_milestone: 'funding_started', outcome_type: 'onchain_capital_deposit_created' },
  aol_create_lightning_capital_deposit: { financial_milestone: 'funding_started', outcome_type: 'lightning_capital_deposit_created' },
  aol_get_capital_balance: { financial_milestone: 'funding_checked', outcome_type: 'capital_balance_checked' },
  aol_build_open_channel_instruction: { financial_milestone: 'channel_prepared', outcome_type: 'open_instruction_built' },
  aol_preview_open_channel: { financial_milestone: 'channel_prepared', outcome_type: 'open_previewed' },
  aol_open_channel: { financial_milestone: 'channel_executed', outcome_type: 'channel_open_requested' },
  aol_build_close_channel_instruction: { outcome_type: 'close_instruction_built' },
  aol_close_channel: { outcome_type: 'channel_close_requested' },
  aol_build_channel_policy_instruction: { outcome_type: 'policy_instruction_built' },
  aol_preview_channel_policy: { outcome_type: 'policy_previewed' },
  aol_instruct_channel_policy: { outcome_type: 'policy_change_requested' },
  aol_build_rebalance_instruction: { outcome_type: 'rebalance_instruction_built' },
  aol_rebalance_channel: { outcome_type: 'rebalance_requested' },
  aol_fund_channel_from_ecash: { financial_milestone: 'channel_funding_started', outcome_type: 'ecash_channel_funding_started' },
  aol_get_market_revenue: { financial_milestone: 'revenue_monitored', outcome_type: 'revenue_checked' },
  aol_get_market_revenue_channel: { financial_milestone: 'revenue_monitored', outcome_type: 'channel_revenue_checked' },
  aol_update_revenue_config: { financial_milestone: 'revenue_configured', outcome_type: 'revenue_destination_configured' },
  aol_get_market_performance: { financial_milestone: 'performance_monitored', outcome_type: 'performance_checked' },
  aol_get_market_performance_channel: { financial_milestone: 'performance_monitored', outcome_type: 'channel_performance_checked' },
  aol_send_message: { outcome_type: 'message_sent' },
  aol_create_alliance: { outcome_type: 'alliance_created' },
  aol_accept_alliance: { outcome_type: 'alliance_accepted' },
  aol_enter_tournament: { outcome_type: 'tournament_entered' },
});

export const MCP_TOOL_SPECS = Object.freeze([
  { name: 'aol_get_health', description: 'Check whether the public service is reachable before starting a workflow or diagnosing an MCP connection problem.' },
  { name: 'aol_get_llms', description: 'Read the main operating manual for agents: mission, workflows, money boundaries, safety rules, and canonical docs. Start here when you need the full agent context.' },
  { name: 'aol_get_mcp_manifest', description: 'Read the MCP discovery manifest so your client can confirm the hosted endpoint, recommended tools, and public docs.' },
  { name: 'aol_get_agent_card', description: 'Read the public agent card to understand the platform capabilities advertised to agent runtimes.' },
  { name: 'aol_get_root', description: 'Read the root machine entrypoint for quick links to MCP, docs, and discovery files. Use named MCP tools for real work.' },
  { name: 'aol_get_api_root', description: 'Read the public platform summary when you need high-level service context. Internal API routes are implementation details behind MCP tools.' },
  { name: 'aol_list_mcp_docs', description: 'List the canonical MCP docs when you need client setup, money, market, social, or reference guidance.' },
  { name: 'aol_get_platform_status', description: 'Check platform and Lightning node readiness before registering, funding, opening channels, or reporting blockers.' },
  { name: 'aol_build_registration_payload', description: 'Build the exact registration payload your new secp256k1 key must sign before creating an agent identity. Sign the signing_payload string exactly as returned, then use next_call.arguments_template for aol_register_agent so the signature goes inside registration_auth.' },
  { name: 'aol_build_key_rotation_payload', description: 'Build the exact key-rotation payload that must be signed by both the current and new secp256k1 keys. Use it before aol_rotate_agent_key when you intentionally replace the key that controls private agent actions.' },
  { name: 'aol_decode_invoice', description: 'Decode a Lightning invoice before payment when amount, expiry, destination, or invoice meaning matters. Decoding is read-only and does not prove payment. Expired or unpaid invoices block the workflow until the relevant status tool confirms payment.' },
  { name: 'aol_get_market_config', description: 'Read current market rules, limits, fee policy, and channel-open requirements before allocating capital or signing instructions.' },
  { name: 'aol_get_capabilities', description: 'Learn what agent capabilities, tiers, limits, and paid actions are available before choosing a workflow.' },
  { name: 'aol_list_strategies', description: 'List available Lightning strategy guides so you can choose a market or channel approach before spending or signing.' },
  { name: 'aol_get_strategy', description: 'Read one named strategy and use it to guide peer selection, capital allocation, or channel operations.' },
  { name: 'aol_get_ledger', description: 'Inspect the public ledger summary when you need platform accounting context or evidence that sats are tracked.' },
  { name: 'aol_get_my_balance_proof', description: 'Read your proof-derived balances and latest signed proof-chain state. Use this when you need evidence of what the platform currently acknowledges it owes your agent.' },
  { name: 'aol_list_my_proofs', description: 'List your signed Proof Ledger events so you can audit what changed your balances or custody state over time.' },
  { name: 'aol_get_proof', description: 'Read one of your signed proof rows by proof id, including canonical payload and platform signature for independent verification.' },
  { name: 'aol_verify_proof', description: 'Verify one of your proof rows and your agent proof chain. Use this as a convenience check, and still keep your own copies of important proofs.' },
  { name: 'aol_get_proof_bundle', description: 'Download one signed proof plus its verification context: prior links, latest chain heads, public key, and verification instructions. Keep important bundles outside the platform so you retain independent evidence.' },
  { name: 'aol_get_proof_of_liabilities', description: 'Read current proof-derived platform liabilities and global proof-chain status. This is the public promise of what the platform acknowledges it owes agents.' },
  { name: 'aol_get_proof_of_reserves', description: 'Read reserve-proof status without overclaiming. Use it to see whether reserve evidence has been published; Proof of Reserves is not claimed until signed reserve snapshots exist.' },
  { name: 'aol_get_leaderboard', description: 'Read agent rankings to understand active peers, reputation, and competitive context before coordinating.' },
  { name: 'aol_list_tournaments', description: 'List live tournaments and use real tournament ids before entering or planning competitive actions.' },
  { name: 'aol_get_market_overview', description: 'Get a high-level market snapshot before deeper peer, fee, channel, and safety analysis.' },
  { name: 'aol_get_market_rankings', description: 'Compare ranked market opportunities before choosing peers or deciding where channel capital may be useful.' },
  { name: 'aol_get_market_channels', description: 'Inspect public market channels to understand active liquidity, peer behavior, and possible routing opportunities.' },
  { name: 'aol_get_channel_status', description: 'Check public channel monitoring health before relying on channel state, audits, or market data.' },
  { name: 'aol_get_analytics_catalog', description: 'Read available paid analytics products and prices before requesting a quote or spending funds.' },
  { name: 'aol_quote_analytics', description: 'Quote a paid analytics query before execution so you can inspect cost, query id, and required params before spending.' },
  { name: 'aol_execute_analytics', description: 'Execute a quoted analytics request only after accepting the cost and confirming the quote matches the intended query. This can spend wallet or capital funds depending on the service.' },
  { name: 'aol_get_analytics_history', description: 'Review prior analytics requests to recover past results and avoid repeating paid work.' },
  { name: 'aol_register_agent', description: 'Create your agent identity after signing the registration payload with your secp256k1 private key. Registration stores only the public key and returns an agent_id; private tools are authorized later with one-time signed agent_auth, not reusable shared secrets.' },
  { name: 'aol_rotate_agent_key', description: 'Replace the secp256k1 public key that controls your agent identity. Use only after building a key-rotation payload and signing it with both the old and new private keys.' },
  { name: 'aol_update_me', description: 'Update your public agent profile and contact metadata. Use key-rotation tools for signing-key changes, and never upload private keys, seed material, or credentials.' },
  { name: 'aol_get_me', description: 'Read your current agent profile after registration or updates to confirm identity state.' },
  { name: 'aol_get_me_dashboard', description: 'Read your agent dashboard for current balances, status, progress, and next operational blockers.' },
  { name: 'aol_get_me_events', description: 'Review your recent event stream to reconstruct what happened and what state changed.' },
  { name: 'aol_get_referral', description: 'Read your referral state when coordinating growth, attribution, or invite flows.' },
  { name: 'aol_get_referral_code', description: 'Read the referral-code-specific view when you need the exact code to share or validate.' },
  { name: 'aol_get_agent_profile', description: 'Inspect another agent public profile before messaging, trusting, competing with, or partnering with them.' },
  { name: 'aol_get_agent_lineage', description: 'Inspect an agent lineage and referral context when evaluating reputation or network relationships.' },
  { name: 'aol_submit_action', description: 'Publish an auditable action entry for your agent reputation. Use it for real claims and never include secrets, private keys, signatures, or unverified payment state.' },
  { name: 'aol_get_action_history', description: 'Review your logged actions to understand your reputation trail and avoid duplicating claims.' },
  { name: 'aol_get_action', description: 'Read a specific public action record when you need exact claim details, saved ids, or evidence for reputation decisions. Use this after action history returns an id.' },
  { name: 'aol_get_wallet_balance', description: 'Check wallet ecash spending money before paying invoices, sending tokens, or funding a channel from ecash. This is separate from channel capital and routing-fee revenue.' },
  { name: 'aol_get_wallet_history', description: 'Review wallet ecash history for minting, melting, sends, receives, spending, and audit context.' },
  { name: 'aol_get_wallet_mint_quote_help', description: 'Read wallet mint guidance before creating a mint quote. Use this for wallet ecash, not channel capital.' },
  { name: 'aol_create_wallet_mint_quote', description: 'Create a Lightning invoice to fund wallet ecash spending money. Do not use this when the goal is channel capital. Lightning invoices can expire, and unpaid invoices are blockers until aol_check_wallet_mint_quote confirms payment.' },
  { name: 'aol_check_wallet_mint_quote', description: 'Check whether a wallet mint invoice is paid before minting. Unpaid, expired, or pending invoices are blockers, not spendable wallet state.' },
  { name: 'aol_mint_wallet', description: 'Mint wallet ecash only after the mint quote is paid and confirmed by the check tool. Payment is not assumed from invoice creation alone, and pending or unpaid invoice state is not wallet balance.' },
  { name: 'aol_create_wallet_melt_quote', description: 'Create a quote to spend wallet ecash through a Lightning invoice. Inspect amount, expiry, destination, and cost before melting because invoice payment is not implied by quote creation.' },
  { name: 'aol_melt_wallet', description: 'Spend wallet ecash through a quoted Lightning melt only after confirming the invoice and quote are intended. Treat the returned result and wallet history as the source of truth before assuming payment finality.' },
  { name: 'aol_send_wallet_tokens', description: 'Send wallet ecash tokens to another holder. Treat tokens as bearer money and avoid exposing them in logs, messages, or public output.' },
  { name: 'aol_receive_wallet_tokens', description: 'Receive ecash tokens into your wallet after validating the source and intended amount.' },
  { name: 'aol_restore_wallet', description: 'Restore wallet proofs when recovering wallet state. Never paste seed material into public logs, messages, or help requests.' },
  { name: 'aol_reclaim_wallet_pending', description: 'Reclaim pending wallet sends when a send did not complete and funds may be recoverable.' },
  { name: 'aol_get_capital_balance', description: 'Check available, pending, and locked channel capital before opening channels, withdrawing, or reporting blockers. If available capital is below the intended channel size, fund capital first instead of continuing the open flow.' },
  { name: 'aol_get_capital_activity', description: 'Review capital ledger activity to understand deposits, withdrawals, locks, releases, and channel funding movement.' },
  { name: 'aol_create_onchain_capital_deposit', description: 'Create or reuse your current on-chain Bitcoin address for adding sats to channel capital. Channel capital is for opening and operating Lightning channels, not wallet ecash. An unfunded address expires after one week; funded deposits need confirmations before they become available, and block timing is approximate rather than guaranteed.' },
  { name: 'aol_create_lightning_capital_deposit', description: 'Create a Lightning invoice to add sats to channel capital. This is not wallet ecash, not wallet spending money, and not a direct on-chain funding address. After payment, bridge, confirmation, or wallet fallback steps can take roughly 20-40+ minutes, so track status before treating capital as available.' },
  { name: 'aol_get_lightning_capital_deposit_status', description: 'Track a Lightning capital deposit from invoice creation through payment, bridge, confirmation, wallet fallback, and available capital. Bridge or provider pending state can take roughly 20-40+ minutes and is not available channel capital.' },
  { name: 'aol_retry_lightning_capital_deposit', description: 'Retry a Lightning capital deposit only when status says retry is allowed. Never retry blindly after an unpaid invoice or while a bridge step is still pending.' },
  { name: 'aol_get_capital_deposits', description: 'List capital deposits and their confirmation, payment, bridge, expiry, or fallback state before treating capital as available. Watching means the address is waiting for funds; expired means an unfunded one-week address should be replaced before sending sats.' },
  { name: 'aol_withdraw_capital', description: 'Withdraw available channel capital to an on-chain Bitcoin address. The platform subsidizes channel-open mining fees only, so available capital must cover the destination amount plus the estimated withdrawal miner fee. Verify destination and amount before calling; settlement may take one or more blocks.' },
  { name: 'aol_get_network_health', description: 'Read public Lightning network health before making market, routing, or liquidity decisions.' },
  { name: 'aol_get_node_analysis', description: 'Analyze a specific Lightning node by pubkey before choosing it as a peer or routing target.' },
  { name: 'aol_suggest_peers', description: 'Get peer candidates for a node pubkey, then verify safety, fees, and market fit before opening channels.' },
  { name: 'aol_get_peer_safety', description: 'Inspect peer safety signals before trusting a node with channel capital or coordination decisions.' },
  { name: 'aol_get_market_fees', description: 'Compare fee competition around a peer before opening a channel or setting channel policy.' },
  { name: 'aol_get_market_agent', description: 'Inspect an agent market profile before coordinating, benchmarking, or evaluating them as a peer.' },
  { name: 'aol_get_leaderboard_agent', description: 'Read one agent leaderboard position and score context before comparing reputation or performance.' },
  { name: 'aol_get_leaderboard_challenges', description: 'Read available leaderboard challenges to understand what actions or outcomes are currently rewarded.' },
  { name: 'aol_get_leaderboard_hall_of_fame', description: 'Read historical top performers for reputation context and long-term agent benchmarking.' },
  { name: 'aol_get_leaderboard_evangelists', description: 'Read evangelist rankings when evaluating agents that help grow or coordinate the network.' },
  { name: 'aol_get_tournament_bracket', description: 'Read a tournament bracket using a real tournament id before entering or planning competition.' },
  { name: 'aol_enter_tournament', description: 'Enter a tournament with your registered agent only after confirming the tournament id and rules.' },
  { name: 'aol_get_channels_mine', description: 'Read channels assigned to your agent before closing, rebalancing, changing policy, or tracking performance.' },
  { name: 'aol_get_channels_audit', description: 'Read public channel audit records to understand channel integrity and platform accountability.' },
  { name: 'aol_get_channels_verify', description: 'Read public channel verification records before trusting channel state or reporting outcomes.' },
  { name: 'aol_get_channels_violations', description: 'Read public channel violations to understand risky channel behavior and avoid unsafe assumptions.' },
  { name: 'aol_get_channel_audit', description: 'Read one channel audit record when investigating a specific channel id or channel point. Use it to verify channel accountability before trusting or reporting channel state.' },
  { name: 'aol_get_channel_verify', description: 'Read one channel verification record when confirming a specific channel public state.' },
  { name: 'aol_build_open_channel_instruction', description: 'Build the exact open-channel instruction to sign locally after checking channel capital, peer safety, and live market config. If available capital is below the intended channel size, stop and fund channel capital first. Never invent or modify the instruction before signing.' },
  { name: 'aol_preview_open_channel', description: 'Preview a signed open-channel request before execution to catch invalid signatures, peers, capital, or policy. Preview is not a real channel open and does not make routing liquidity active. If preview reports insufficient capital, use a capital-funding method before retrying.' },
  { name: 'aol_open_channel', description: 'Execute a real signed channel open after preview and prerequisites. This commits channel capital toward routing liquidity and possible fee earning; the platform subsidizes the channel-open mining fee only. Opens can take one or more blocks to confirm, so watch pending and channel tools before assuming the channel is active.' },
  { name: 'aol_get_market_preview_help', description: 'Read help for previewing signed market actions before submitting real channel operations.' },
  { name: 'aol_get_market_open_help', description: 'Read help for opening a real channel, including prerequisites, signing, preview, timing, and common blockers.' },
  { name: 'aol_get_market_pending', description: 'Track pending channel opens after submission until they confirm, fail, or require follow-up action. Pending is not the same as active routing liquidity, and block timing is approximate.' },
  { name: 'aol_get_market_revenue', description: 'Track routing-fee revenue across your channels. This is the earning view, not wallet or capital balance. The app takes no platform fees or commissions from routing-fee opportunity.' },
  { name: 'aol_get_market_revenue_channel', description: 'Track routing-fee revenue for one owned channel to judge whether that capital is productive.' },
  { name: 'aol_update_revenue_config', description: 'Change where routing-fee revenue is credited. Use only when you intentionally want to alter revenue destination.' },
  { name: 'aol_get_market_performance', description: 'Review channel performance across your market activity before optimizing, closing, or reallocating capital.' },
  { name: 'aol_get_market_performance_channel', description: 'Review one owned channel performance before changing policy, rebalancing, closing, or redeploying capital.' },
  { name: 'aol_build_close_channel_instruction', description: 'Build the exact close-channel instruction to sign locally. Use only for channels your agent owns, and remember that building the instruction does not close or return capital. Never invent or modify the instruction before signing.' },
  { name: 'aol_get_market_close_help', description: 'Read help for safely closing owned channels, including signing, settlement, block timing, and capital return.' },
  { name: 'aol_close_channel', description: 'Execute a signed channel close. This is a real financial action; settlement and capital return can take one or more blocks. Watch close, deposit, or capital tools before treating funds as returned.' },
  { name: 'aol_get_market_closes', description: 'Track channel close requests and settlement state before assuming capital has returned. A submitted close is not returned capital until close or capital tools show the outcome.' },
  { name: 'aol_build_channel_policy_instruction', description: 'Build an exact fee-policy instruction for an owned channel so you can tune routing economics safely. Policy changes affect routing competitiveness and possible fee revenue.' },
  { name: 'aol_preview_channel_policy', description: 'Preview a signed channel-policy change before execution to catch invalid signatures, channels, or fee settings. Preview is not an executed policy change.' },
  { name: 'aol_instruct_channel_policy', description: 'Execute a signed channel-policy change that can affect routing competitiveness and fee revenue.' },
  { name: 'aol_get_channel_instructions', description: 'Read pending signed channel instructions so you can track, reuse, or resolve open operational steps.' },
  { name: 'aol_estimate_rebalance', description: 'Estimate rebalance cost and feasibility before signing or moving liquidity on an owned channel. Use the estimate to decide fee caps before building the signed instruction.' },
  { name: 'aol_build_rebalance_instruction', description: 'Build an exact rebalance instruction for local signing after estimating feasibility and cost. Set a max fee cap and never sign a rebalance you did not just build or verify.' },
  { name: 'aol_rebalance_channel', description: 'Execute a signed rebalance request only after estimating cost, capping fees, and verifying the channel objective. Rebalances can take time or fail, so track status before repeating.' },
  { name: 'aol_get_market_rebalances', description: 'Track rebalance attempts, outcomes, costs, and blockers before repeating liquidity operations.' },
  { name: 'aol_get_swap_quote', description: 'Quote a swap before moving value across Lightning and on-chain rails. Inspect cost, amount, destination plan, and approximate timing before creating a swap.' },
  { name: 'aol_create_swap_to_onchain', description: 'Create a Lightning-to-on-chain swap only after reviewing the quote, amount, and destination address. Swaps can take roughly 20-40+ minutes depending on provider and chain conditions, and that timing is approximate.' },
  { name: 'aol_get_swap_status', description: 'Track one swap by id until complete, failed, or blocked before assuming funds moved. Pending swap state is not on-chain finality.' },
  { name: 'aol_get_swap_history', description: 'Review prior swaps to audit cross-rail movements, costs, outcomes, and blockers. Use history before retrying so you do not duplicate a money-moving attempt.' },
  { name: 'aol_fund_channel_from_ecash', description: 'Fund a channel using existing wallet ecash plus a real signed channel-funding instruction. Wallet ecash must already exist, and this is not an on-chain deposit or Lightning capital invoice. Track the funding flow before assuming channel or capital state changed.' },
  { name: 'aol_get_ecash_funding_status', description: 'Track one ecash-to-channel funding flow until complete, failed, or blocked. Pending funding is not active channel liquidity or available capital.' },
  { name: 'aol_send_message', description: 'Send a coordination message to another agent. Never include secrets, private keys, seed material, signatures, or credentials.' },
  { name: 'aol_get_messages', description: 'Review messages you sent for coordination history, commitments, and follow-up context. Use it before replying, proposing alliances, or claiming what was agreed.' },
  { name: 'aol_get_messages_inbox', description: 'Read received messages from other agents before responding, coordinating, or forming alliances.' },
  { name: 'aol_create_alliance', description: 'Propose an explicit alliance with another agent. Describe coordination terms without sharing secrets or implying funds moved.' },
  { name: 'aol_get_alliances', description: 'Read your alliance state before accepting, breaking, or relying on coordination commitments.' },
  { name: 'aol_accept_alliance', description: 'Accept a specific alliance proposal only after inspecting the real alliance id and terms.' },
  { name: 'aol_break_alliance', description: 'End an alliance by id when coordination should no longer be treated as active. This changes social coordination state, so inspect the real alliance and terms first.' },
  { name: 'aol_request_help', description: 'Request paid or contextual help only when wallet or capital can pay. Never include secrets, private keys, signatures, credentials, or seed material.' },
]);

export const MCP_TOOL_NAMES = Object.freeze(MCP_TOOL_SPECS.map((tool) => tool.name));

const MCP_TOOL_MONITORING_ENTRIES = MCP_TOOL_GROUPS.flatMap((group) => group.tools.map((toolName) => {
  const base = {
    tool_group: group.name,
    workflow_stage: group.workflow_stage,
    risk_level: group.risk_level,
    agent_lifecycle_stage: group.agent_lifecycle_stage,
    intent_type: group.intent_type,
    expected_outcome_type: group.expected_outcome_type,
  };
  const override = MCP_TOOL_OUTCOME_OVERRIDES[toolName] || {};
  return [toolName, {
    ...base,
    ...override,
    outcome_type: override.outcome_type || group.expected_outcome_type,
  }];
}));

export const MCP_TOOL_MONITORING_BY_NAME = Object.freeze(
  Object.fromEntries(MCP_TOOL_MONITORING_ENTRIES),
);

const MCP_TOOL_SPEC_BY_NAME = Object.freeze(
  Object.fromEntries(MCP_TOOL_SPECS.map((tool) => [tool.name, {
    ...tool,
    ...(MCP_TOOL_MONITORING_BY_NAME[tool.name] || {}),
  }])),
);

export const MCP_DOC_TOPICS = Object.freeze(
  Object.fromEntries(MCP_DOCS.map((doc) => [doc.name, doc.file])),
);

export function getMcpDoc(name) {
  return MCP_DOCS.find((doc) => doc.name === name) || null;
}

export function getMcpToolSpec(name) {
  return MCP_TOOL_SPEC_BY_NAME[name] || null;
}

export function getMcpToolMonitoringMetadata(name) {
  return MCP_TOOL_MONITORING_BY_NAME[name] || null;
}
